amazon:
  associateId: habuma-20

logging:
  level:
    root: INFO

---

spring:
  profiles: development

logging:
  path: /var/logs
  file : test.log
  level:
    root: DEBUG
    org :
      springframework:
        security: DEBUG

